#! /usr/bin/env python3
#
# SPDX-License-Identifier: MIT

from pathlib import Path

SRCDIR = Path(__file__).parent.parent.parent
MANIFEST = SRCDIR / "wpeview" / "src" / "main" / "AndroidManifest.xml"
SERVICES = SRCDIR / "wpeview" / "src" / "main" / "java" / "org" / "wpewebkit" / "wpe" / "services" / "WPEServices.java"


def make_service(tree, kind: str, instance: int):
    service = tree.createElement("service")
    service.setAttribute("android:name", f"org.wpewebkit.wpe.services.WPEServices${kind}ProcessService{instance}")
    service.setAttribute("android:process", f":WPE{kind}Process{instance}")
    return service


def remove_nodes(node, predicate, recurse: bool = False):
    nodes_to_remove = {child for child in node.childNodes if predicate(child)}
    for child in nodes_to_remove:
        node.removeChild(child)
        child.unlink()

    if recurse:
        for child in node.childNodes:
            remove_nodes(child, predicate, recurse)


def is_empty_node(node) -> bool:
    return node.nodeType == node.TEXT_NODE and len(node.nodeValue.strip()) == 0


def is_service_node(node) -> bool:
    return node.nodeType == node.ELEMENT_NODE and node.tagName == "service" and \
        node.getAttribute("android:name").startswith("org.wpewebkit.wpe.services.WPEServices$")


def update_manifest(path: Path, num_services: int) -> None:
    from xml.dom import minidom
    xml_text = path.read_text(encoding="utf-8")
    with minidom.parseString(xml_text) as tree:
        app = tree.getElementsByTagName("application")[0]

        remove_nodes(app, is_service_node)
        for i in range(num_services):
            app.appendChild(make_service(tree, "Network", i))
            app.appendChild(make_service(tree, "Web", i))

        remove_nodes(tree, is_empty_node, True)
        with path.open("w") as output:
            tree.writexml(output, encoding="utf-8", newl="\n", addindent="\t")


SERVICES_FILE_TEMPLATE = """\
// Do not edit. Generated by tools/scripts/update-services.py
package org.wpewebkit.wpe.services;

public class WPEServices {{
{services}
    public static final int MAX_AUX_PROCESSES = {count};
}}
"""


SERVICE_TEMPLATE = """\
    public static final class WebProcessService{index} extends WebProcessService {{}}
    public static final class NetworkProcessService{index} extends NetworkProcessService {{}}
"""


def update_services(path: Path, num_services: int) -> None:
    services = ""
    for i in range(num_services):
        services += SERVICE_TEMPLATE.format(index=i)
    with path.open("w", encoding="utf-8") as output:
        output.write(SERVICES_FILE_TEMPLATE.format(services=services, count=num_services))


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Edit WPE services definitions")
    parser.add_argument("--num-services", "-n", type=int, required=True,
                        help="Maximum number of service instances.")
    parser.add_argument("--manifest", metavar="PATH", type=Path, default=MANIFEST,
                        help=f"Path to AndroidManifest.xml file ({MANIFEST})")
    parser.add_argument("--services", metavar="PATH", type=Path, default=SERVICES,
                        help=f"Path to WPEServices.java file ({SERVICES})")
    options = parser.parse_args()

    update_manifest(options.manifest, options.num_services)
    update_services(options.services, options.num_services)


if __name__ == "__main__":
    main()
