name: Check
on: workflow_call

jobs:
  check-format:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Java™ Setup
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 11076708
          log-accepted-android-sdk-licenses: false
      - name: Check Code Format
        run: ./gradlew checkFormat

  check-jni:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Java™ Setup
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Check JNI
        run: |
          cd tools/jni-test && \
          cmake -S. -Bbuild && \
          cmake --build build --target run
