name: Lint
on:
  workflow_call:
    inputs:
      build_type:
        required: true
        type: string

jobs:
  lint-checks:
      runs-on: ubuntu-24.04
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Fetch Dependencies (WPE Bootstrap)
          run: python3 tools/scripts/bootstrap.py -a all
        - name: Java™ Setup
          uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: 17
        - name: Setup Android SDK
          uses: android-actions/setup-android@v3
          with:
            log-accepted-android-sdk-licenses: false
            packages: "tools platform-tools cmake;3.31.1"
        - name: Lint checks
          run: ./gradlew lint${{ inputs.build_type }}
