name: Publish to Maven Central

on:
 workflow_dispatch: # Allow manual trigger

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch Dependencies (WPE Bootstrap)
        run: python3 tools/scripts/bootstrap.py -a all
      - name: Java™ Setup
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build and publish
        run: ./gradlew wpeview:publishReleasePublicationToOSSRHRepository
        env:
          OSSRH_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          SIGNING_KEY: ${{ secrets.PGP_CENTRAL_SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.PGP_CENTRAL_SIGNING_KEY_PASSPHRASE }}
