name: Publish to Maven Central

on:
 workflow_dispatch: # Allow manual trigger

jobs:
  publish:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch Dependencies (WPE Bootstrap)
        run: python3 tools/scripts/bootstrap.py -a all
      - name: Java™ Setup
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          log-accepted-android-sdk-licenses: false
          packages: "tools platform-tools cmake;3.31.1"
      - name: Build and publish
        run: ./gradlew wpeview:publishMavenPublicationToMavenCentralRepository
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.PGP_CENTRAL_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.PGP_CENTRAL_SIGNING_KEY_PASSPHRASE }}
