name: Run WebDriver Tests

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build Latest Preview]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        api-level: [33]
        arch: [x86_64]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Download latest WebDriver Preview
        run: wget https://github.com/Igalia/wpe-android/releases/download/latest-preview/webdriver-latest.apk -O webdriver-latest.apk

      - name: Run Selenium and W3C tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            adb install webdriver-latest.apk
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -r tools/scripts/webkitpy/requirements.txt
            tools/scripts/run-webdriver-tests
