name: Test
on: workflow_call

jobs:
  instrumentation-tests:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Java™ Setup
          uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: 17
        - name: Fetch Dependencies (WPE Bootstrap)
          run: python3 tools/scripts/bootstrap.py -a x86_64
        - name: Remove layouttests and webdrivertests
          run: |
            rm -rf layouttests
            rm -rf webdrivertests
        - name: Build Project
          run: ./gradlew wpe:build
        - name: Enable KVM
          run: |
            echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
            sudo udevadm control --reload-rules
            sudo udevadm trigger --name-match=kvm
        - name: Run Instrumentation Tests
          uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: 34
            arch: x86_64
            target: google_apis
            force-avd-creation: false
            emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
            disable-animations: true
            script: ./gradlew wpe:connectedDebugAndroidTest --stacktrace
        - name: Create Test Summary
          uses: test-summary/action@v2
          with:
            paths: '**/*est-results/**/*.xml'
            show: "pass, fail, skip"
