name: Test
on: workflow_call

env:
  apiLevel: '33'
  arch: 'x86_64'

jobs:
  instrumentation-tests:
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Java™ Setup
          uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: 17
        - name: Fetch Dependencies (WPE Bootstrap)
          run: python3 tools/scripts/bootstrap.py -a x86_64
        - name: Remmove layouttests and webdrivertests
          run: |
            rm -rf layouttests
            rm -rf webdrivertests
        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@v4
        - name: Enable KVM
          run: |
            echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
            sudo udevadm control --reload-rules
            sudo udevadm trigger --name-match=kvm
        - name: AVD cache
          uses: actions/cache@v4
          id: avd-cache
          with:
            path: |
              ~/.android/avd/*
              ~/.android/adb*
            key: avd-${{ env.apiLevel }}
        - name: Create AVD and generate snapshot for caching
          if: steps.avd-cache.outputs.cache-hit != 'true'
          uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: ${{ env.apiLevel }}
            arch: ${{ env.arch }}
            force-avd-creation: false
            emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
            disable-animations: false
            script: echo "Generated AVD snapshot for caching."
        - name: Instrumented Tests
          uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: ${{ env.apiLevel }}
            arch: ${{ env.arch }}
            emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
            script: ./gradlew wpe:connectedDebugAndroidTest
